CREATE DATABASE IF NOT EXISTS OAKLAND_STREET_CAM_AI_DETECTION;

USE OAKLAND_STREET_CAM_AI_DETECTION;


DROP TABLE IF EXISTS CAMERA_INFO, DETECTION_CASE, RESOLVED_DETECTION_CASE, DEBUG_EVENT_INFO;



CREATE TABLE IF NOT EXISTS CAMERA_INFO(
    ID INT NOT NULL PRIMARY KEY,
    LOCATION VARCHAR(255) NOT NULL,
    NOTES VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DETECTION_CASE(
    EVENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TIME_RECORDED TIMESTAMP,
    TIME_IDENTIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CAMERA_ID INT,
    VIDEO_PIECE_NAME VARCHAR(255),
    IS_RESOLVED TINYINT(1),
    FOREIGN KEY (CAMERA_ID) REFERENCES CAMERA_INFO(ID)
);

CREATE TABLE IF NOT EXISTS RESOLVED_DETECTION_CASE(
    EVENT_ID INT NOT NULL PRIMARY KEY,
    ENFORCER_ID VARCHAR(50),
    WHEN_RESOLVED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVER_IP VARCHAR(45), -- leave a few extra just in case
    RESOLVER_NOTES VARCHAR(1000),
    IS_IT_CORRECTLY_IDENTIFIED TINYINT(1),
    
    FOREIGN KEY (EVENT_ID) REFERENCES DETECTION_CASE(EVENT_ID)
);

CREATE TABLE IF NOT EXISTS DEBUG_EVENT_INFO(
    EVENT_ID INT NOT NULL PRIMARY KEY,
    DEBUG_NOTES VARCHAR(1000),
    FOREIGN KEY (EVENT_ID) REFERENCES DETECTION_CASE(EVENT_ID)
);



-- SHOW TABLES;
-- DESC CAMERA_INFO;
-- DESC DETECTION_CASE;
-- DESC RESOLVED_DETECTION_CASE;
-- DESC DEBUG_EVENT_INFO;



USE OAKLAND_STREET_CAM_AI_DETECTION;

INSERT INTO CAMERA_INFO(ID, LOCATION, NOTES) VALUES(0, '0 BVD', 'TEST DTASET'),
(1, '1 BVD', 'TEST DTASET'),
(2,'2 BVD', 'TEST DTASET'),
(3, '3 BVD', 'TEST DTASET'),
(4, '4 BVD', 'TEST DTASET'),
(5, '5 BVD', 'TEST DTASET');

INSERT INTO DETECTION_CASE(TIME_RECORDED, CAMERA_ID, VIDEO_PIECE_NAME, IS_RESOLVED) VALUES
(NOW(), 0, 'test0.mp4', 0),
(NOW(), 3, 'test1.mp4', 0),
(NOW(), 3, 'test2.mp4', 0),
(NOW(), 2, 'test3.mp4', 0),
(NOW(), 5, 'test4.mp4', 0),
(NOW(), 5, 'test5.mp4', 0),
(NOW(), 3, 'test6.mp4', 0),
(NOW(), 1, 'test7.mp4', 0),
(NOW(), 3, 'test8.mp4', 0);

INSERT INTO DETECTION_CASE(TIME_RECORDED, CAMERA_ID, VIDEO_PIECE_NAME, IS_RESOLVED) VALUES
(NOW(), 3, 'test9.mp4', 1),(NOW(), 0, 'test10.mp4', 1),(NOW(), 5, 'test11.mp4', 1);

INSERT INTO DETECTION_CASE(TIME_RECORDED, CAMERA_ID, VIDEO_PIECE_NAME, IS_RESOLVED) VALUES
(NOW(), 2, 'test12.mp4', 0);


INSERT INTO RESOLVED_DETECTION_CASE(EVENT_ID, ENFORCER_ID, WHEN_RESOLVED, RESOLVER_IP, RESOLVER_NOTES, IS_IT_CORRECTLY_IDENTIFIED)
SELECT 
    EVENT_ID,
    'zhrmghgwssjrmdtjws',
    NOW(),
    '0.0.0.',
    'government fund +1',
    0
FROM DETECTION_CASE
WHERE IS_RESOLVED = 1;



INSERT INTO DEBUG_EVENT_INFO(EVENT_ID, DEBUG_NOTES) VALUES (1, 'YOLOV11 BONE 3.234343 4.42334 TRASH 3.3434 9.43534'),
(5, 'YOLOV11 BONE 3.234343 4.42334 TRASH 3.3434 9.43534'),
(6, 'YOLOV11 BONE 3.234343 4.42334 TRASH 3.3434 9.43534');


SELECT * FROM CAMERA_INFO;
SELECT * FROM DETECTION_CASE;
SELECT * FROM RESOLVED_DETECTION_CASE;
SELECT * FROM DEBUG_EVENT_INFO;
